# Generated by Django 2.2.5 on 2019-10-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='accounts',
            field=models.ManyToManyField(to='banks.Account'),
        ),
    ]
